### ISSUE TITLE
Max temperature in PID configuration is too restrictive

### ISSUE THREAD

**Issue by gregorychen3** [gregorychen3/espresso-controller#1]
## Description

Trying to set a temperature above 100C in the PID configuration leads to an error that the requested temperature is too high.

This is clearly too restrictive because
- 100C is insufficient for steaming
- With the steam switch on, a factory Rancilio Silvia will heat to 140C (see manual: https://www.ranciliogroupna.com/filebin/images/Downloadables/User_Manuals/Homeline/Silvia_User_Manual_2017.PDF)

## Proposal
Increase the max temperature to 140C.

This will require changes at:
- https://github.com/gregorychen3/espresso-controller/blob/master/ui/src/components/ConfigurationForm.tsx#L17
- https://github.com/gregorychen3/espresso-controller/blob/master/internal/espresso/grpc_controller.go#L122

**Comment by kev-guy** [comment]
Thanks for creating this issue. I'll take a crack at creating a branch and committing new files corresponding to the two you identified.
