### ISSUE TITLE
how to compile to get espresso binary 

### ISSUE THREAD

**Issue by spfeifer222** [gregorychen3/espresso-controller#13]
I like to use different RasPi pin connections, but failed to build `espresso` binary with `make build.ui` command. Could you either

1. describe in detail what I need to install/do to compile successfullly, or
2. compile it for me from my folked repository, or
3. build a more flecxible solution with a config file beside the binary, where the binary is reading from?

Or is there a way to get the stuff running without compiling (e.g. a starting script)?

Thanks in advance,
Seb

**Comment by gregorychen3** [comment]
https://github.com/gregorychen3/espresso-controller#installation

**Comment by gregorychen3** [comment]
Try those installation instructions out. If something specific doesn't work for you, please open a bug issue for it. Otherwise, if nothing else needed, please go ahead and close this issue.

**Comment by spfeifer222** [comment]
I cannot use GPIO3, because it is already in use by another program and must keep at GPIO3. Therefore, I cannot follow the installing instructions with the given setup. Which solution do you suggest?

**Comment by gregorychen3** [comment]
You can use any gpio pins you want; gpio 3 is just the default.

```console
pi@raspberrypi:~ $ ./espresso --help
Control and monitor an espresso machine

Usage:
  espresso [flags]

Flags:
      --boiler-therm-clk-pin int    The GPIO pin connected to the boiler thermometer's max31855 clock (default 4)
      --boiler-therm-cs-pin int     The GPIO pin connected to the boiler thermometer's max31855 chip select, aka chip enable (default 3)
      --boiler-therm-miso-pin int   The GPIO pin connected to the boiler thermometer's max31855 data output (default 2)
  -h, --help                        help for espresso
  -p, --port string                 Port on which the espresso server should listen (default "8080")
  -r, --relay-pin int               The GPIO connected to the relay (default 21)
  -v, --verbose                     verbose output
```

**Comment by spfeifer222** [comment]
Oh, Thanks a lot! This is great. I did not recognized that there is a command line interface.
