### ISSUE TITLE
Ask for advice (hardware related)

### ISSUE THREAD

**Issue by spfeifer222** [gregorychen3/espresso-controller#15]
I 've got the espresso-controller working. However, there is the following issue (which is surely not related to the software, but maybe you could give an advice):

![espresso-controller](https://user-images.githubusercontent.com/46728699/113551000-452bf680-95f4-11eb-8c09-d653619d759b.png)

My starting temperature is about -2000 °C. I assume that some of the hardware is not working correctly (e.g. the thermocouple or amplifier). Maybe one of them is damaged and a case for reclamation? 

I used the hardware suggested in the instructions:

Solid state relay: SSR-40
thermocouple: Type K with green/white cables  (+/-)
thermocouple amplifier: MAX31855 (red-, yellow+ label on the thermocouple connections)

Am I right that the color labelling is only to show the correct polarity (see 
[anschlussfarben-fuer-thermoelemente-deutsch.pdf](https://github.com/gregorychen3/espresso-controller/files/6256992/anschlussfarben-fuer-thermoelemente-deutsch.pdf)), or should the amplifier really match the colored labels (e.g. because of K / °C handling)?

**Comment by gregorychen3** [comment]
Possible causes:
- Low quality thermocouple. Most on the internet are pretty bad. Check the README for a link to a high-quality one. Many weird issues that I faced were solved by using a better thermocouple.
- thermocouple <-> amplifier polarity reversed

Also please look for "WARNING" or "ERROR" messages in the application logs. Thermocouple errors will be output there.

**Comment by spfeifer222** [comment]
I double checked before: reversed polarity is not the issue.

An error I observed is:
`{"level":"error","ts":"2021-04-05T12:41:25.872+0200","msg":"Failed to sample temperature","error":"short to ground"}` 

Does this mean a short from thermocouple to ground? I put isolation between the thermocouple it's screw and the boiler (it's a thermoelement for srewing on), but it's worth checking. However, taking your observations of bad  thermocouples into account, this is my current top of the list.

**Comment by gregorychen3** [comment]
Yup, the thermocouple circuit is shorting out somewhere. I saw a lot of shorts too with low-quality thermocouples.

**Comment by gregorychen3** [comment]
For more information on the errors, please see the documentation for the Max31855 amplifier: https://datasheets.maximintegrated.com/en/ds/MAX31855.pdf

**Comment by gregorychen3** [comment]
Closing for now
