### ISSUE TITLE
Pin layout for MAX31855K

### ISSUE THREAD

**Issue by ghost** [gregorychen3/espresso-controller#16]
Hi there. 

First of all the project looks great. BUUUTTT i currently have a MAX31855K instead of a MAX31855 and the pins on that one are different. Can i use that one? i tried it but at this moment im not getting any data from the thermo. Im probably hooking it up wrong because the labeling is different. Or is there a software change needed?

it's this one:
https://learn.sparkfun.com/tutorials/max31855k-thermocouple-breakout-hookup-guide

**Comment by gregorychen3** [comment]
As far as I can tell they are interchangeable. From the datasheets, they look exactly the same:

- Sparkfun data sheet: https://cdn.sparkfun.com/assets/learn_tutorials/3/3/1/MAX31855_4.pdf
- Adafruit data sheet: https://cdn-shop.adafruit.com/datasheets/MAX31855.pdf

Basically, there are 3 pins you need to connect from the MAX31855K to your RasPi; clock, chip select, and data output.

On the Sparkfun device, they are labelled:
- clock: SCK
- chip select: CS
- data output: SO
