### ISSUE TITLE
espresso is not responsive

### ISSUE THREAD

**Issue by gabrielDiaz-performlab** [gregorychen3/espresso-controller#17]

**Comment by gabrielDiaz-performlab** [comment]
Hi Greg,

First, thanks for sharing this work in progress.  I'm excited to give it a go.

So, I've just tried to follow your installation instructions, but the result when I try and execute espresso v 0.25, I get the error: ` bash: .: espresso: cannot execute binary file`

FWIW, I should add that I am running this on a Pi zero for now, despite your advice.  I don't have a 4 on me.  My hope is that, even if it doesn't run optimally on a zero, it will run.

**Comment by gregorychen3** [comment]
You may have forgotten to run this step in the installation instructions:

```
pi@raspberrypi:~ $ chmod +x espresso
```

Noticing also:
> I try and execute espresso v 0.25

but v0.25 does not exist.

If the above did not resolve your issue, please provide your Pi's system information by pasting the output of `uname -a` here.

**Comment by gregorychen3** [comment]
Closing unless further information needed
