### ISSUE TITLE
Application crashes because of concurrent writes in a map

### ISSUE THREAD

**Issue by luiccn** [gregorychen3/espresso-controller#8]
![Screenshot 2021-03-22 at 09 18 59](https://user-images.githubusercontent.com/9625416/111960213-beedbb80-8aef-11eb-9d1d-6a3aa51a2361.png)

I think I've fixed in this [commit](https://github.com/luiccn/espresso-controller/commit/78892d2304bc7f8cdb3399cbe23fefe6df13fb56#diff-a8f7bdfe76958a4841522c3f4f15edfdea16082b9c73847d76d1443bcae279c8
) on my fork.

**Comment by gregorychen3** [comment]
You are totally right. That map needs a mutex. This will fix it: https://github.com/gregorychen3/espresso-controller/pull/11

Please review when able. 

Thank you!
